Repository siderolabs/extensions, pull requests merged in 2025-07, with the labels that each got.

#745 release(v1.11.0-alpha.3): prepare release
  CHANGELOG.md
Labels: status/ok-to-test, status/ok-to-merge

#747 backport: feat: update dependencies via pkgs
  .kres.yaml
  Makefile
  Pkgfile
  hack/release.toml
  storage/zfs/zfs-tools/patches/tests-fix-S_IFMT-undeclared-at-statx.c.patch
  storage/zfs/zfs-tools/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#748 release(v1.10.5): prepare release
  CHANGELOG.md
Labels: status/ok-to-test, status/ok-to-merge

#750 chore: add tools/pkgs in the release notes
  hack/release.toml
Labels: status/ok-to-test, status/ok-to-merge

#752 fix: TLS Verification failures on Newt
  network/newt/newt.yaml
Labels: status/ok-to-merge

#754 feat: update dependencies
  .kres.yaml
  Makefile
  Pkgfile
  container-runtime/vars.yaml
  guest-agents/vars.yaml
  hack/release.toml
  misc/glibc/vars.yaml
  network/vars.yaml
  nvidia-gpu/vars.yaml
Labels: status/ok-to-test, status/ok-to-merge

#756 feat: add SBOM to some extensions
  .github/workflows/ci.yaml
  .github/workflows/lock.yml
  .github/workflows/slack-notify.yaml
  .github/workflows/stale.yml
  .github/workflows/weekly.yaml
  .kres.yaml
  Makefile
  Pkgfile
  network/tailscale/pkg.yaml
  nvidia-gpu/nonfree/kmod-nvidia/lts/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge

#763 feat: add thunderbolt udev rule
  drivers/thunderbolt/README.md
  drivers/thunderbolt/files/99-thunderbolt.rules
  drivers/thunderbolt/manifest.yaml
  drivers/thunderbolt/pkg.yaml
Labels: status/ok-to-merge

#765 fix: nfsrahead udev rule
  storage/nfsrahead/pkg.yaml
Labels: status/ok-to-merge

#767 feat(ci): add grype scan
  .github/workflows/ci.yaml
  .github/workflows/grype-scan-cron.yaml
  .github/workflows/slack-notify.yaml
  .kres.yaml
  Makefile
  go.work
  go.work.sum
  internal/grype-scan/go.mod
  internal/grype-scan/go.sum
  internal/grype-scan/pkg.yaml
  nvidia-gpu/nonfree/kmod-nvidia/production/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge, integration/grype

#772 release(v1.10.6): prepare release
  CHANGELOG.md
Labels: status/ok-to-test, status/ok-to-merge

#770 docs: add more extension SBOMs
  dvb/cx23885/pkg.yaml
  dvb/dvb-m88ds3103/pkg.yaml
  firmware/intel-ucode/pkg.yaml
  guest-agents/qemu-guest-agent/pcre2/pkg.yaml
  guest-agents/vmtoolsd-guest-agent/pkg.yaml
  nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/libseccomp/pkg.yaml
  nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/lts/pkg.yaml
  nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/production/pkg.yaml
  nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml
  power/nut-client/pkg.yaml
  storage/iscsi-tools/open-iscsi/pkg.yaml
  storage/nfsrahead/libevent/pkg.yaml
  storage/nfsrahead/sqlite/pkg.yaml
  storage/zfs/zfs-tools/pkg.yaml
  tools/nvme-cli/libnvme/pkg.yaml
  tools/nvme-cli/pkg.yaml
Labels: status/ok-to-test, status/ok-to-merge, integration/grype
